---
#This role installs and configures the DHCP server

- name: Create pxelinux directory
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory
    group: "{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
  become: true 

- name: Install dnsmasq
  package:
    name: dnsmasq
  become: true

- name: Comment/uncomment options in dnsmasq.conf
  lineinfile:
    path: /etc/dnsmasq.conf
    backrefs: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: true
  with_items:
    - { regexp: '#log-dhcp', line: 'log-dhcp' }
    - { regexp: 'conf-dir=/etc/dnsmasq.d', line: '#conf-dir=/etc/dnsmasq.d' }

# This is just an example configuration. Modify to match your requirements.

- name: Add DHCP configuration to dnsmasq.conf
  lineinfile:
    path: /etc/dnsmasq.conf
    line: "{{ item }}"
  become: true
  with_items:
      - 'interface=eth1'
      - 'dhcp-range=192.168.39.51,192.168.39.70,7d'
      - 'enable-tftp'
      - 'tftp-root=/var/lib/tftpboot'
      - 'dhcp-userclass=set:ENH,iPXE'
      - 'dhcp-boot=tag:!ENH,pxelinux.0,servername,192.168.39.2'

- name: Systemctl commands for dnsmasq
  systemd:
    name: dnsmasq
    daemon-reload: yes
    state: started
    enabled: yes
  become: true
